#pragma once

#define stringify(s) #s
#define xstringify(s) stringify(s)


#define FILEVER_MAJOR 0
#define FILEVER_MINOR 9
#define FILEVER_REVISION 0
#define FILEVER_BUILD 1

#define PRODVER_MAJOR 1
#define PRODVER_MINOR 0
#define PRODVER_REVISION 0
#define PRODVER_BUILD 1

#define FILEVER			FILEVER_MAJOR,FILEVER_MINOR,FILEVER_REVISION,FILEVER_BUILD
#define PRODUCTVER		PRODVER_MAJOR,PRODVER_MINOR,PRODVER_REVISION,PRODVER_BUILD
#define STRFILEVER		xstringify(FILEVER)
#define STRPRODUCTVER	xstringify(PRODUCTVER)

#define FILEVER_DOTSEPARATED FILEVER_MAJOR.FILEVER_MINOR.FILEVER_REVISION.FILEVER_BUILD
#define PRODUCTVER_DOTSEPARATED		PRODVER_MAJOR.PRODVER_MINOR.PRODVER_REVISION.PRODVER_BUILD

#define TESTAPP_FILEVERSION _T(xstringify(FILEVER_DOTSEPARATED))
#define TESTAPP_PRODUCTVERSION  _T(xstringify(PRODUCTVER_DOTSEPARATED))

#define TESTAPP_DESC_PREFIX L"MaxsUtil "
#define TESTAPP_DESC_PREFIX_LEN (ARRAYSIZE(TESTAPP_DESC_PREFIX)-1)
#define TESTAPP_PRODUCTNAME_PREFIX L"Maximilian's "
#define TESTAPP_PRODUCTNAME_PREFIX_LEN (ARRAYSIZE(TESTAPP_PRODUCTNAME_PREFIX)-1)
#define TESTAPP_COMPANY_PREFIX L"Maximilian "
#define TESTAPP_COMPANY_PREFIX_LEN (ARRAYSIZE(TESTAPP_COMPANY_PREFIX)-1)
